### ISSUE TITLE
windows-msvc rust support

### ISSUE THREAD

**Issue by kcking** [facebook/buck2-prelude#6]
Changing the cxx toolchain to use `link` on windows appears to make the rust windows msvc target work. Is there interest in supporting this toolchain from the buck2 team?

**Comment by ndmitchell** [comment]
Yes :) - is that really the only change required, or anything else too?

**Comment by kcking** [comment]
Yep, that's it! Though I just tested a simple hello world `rust_binary` and `rust_test`

**Comment by kcking** [comment]
Scratch that -- I also had to change the _DEFAULT_TRIPLE to be `<arch>-pc-windows-mscv` on windows.

**Comment by ndmitchell** [comment]
Let's close this issue in favour of https://github.com/facebook/buck2/issues/141 then we can keep everything in one place.
